                                                        using 
                                                        System
                                                        .
                                                        Collections
                                                        ;
                                                        using 
                                                        System
                                                        .
                                                        Collections
                                                        .
                                                        Generic
                                                        ;
                                                        using 
                                                        UnityEngine
                                                        ;
                                                        public 
                                                        class
                                                        PifPafSkurwysynu 
                                                        : 
                                                        MonoBehaviour
                                                        {
                                                        public 
                                                        GameObject 
                                                        prefabToShoot
                                                        ;
                                                        public 
                                                        Transform 
                                                        launchPoint
                                                        ;
                                                        public 
                                                        float 
                                                        shootingForce 
                                                        = 
                                                        10f
                                                        ;
                                                        public 
                                                        float 
                                                        shootingInterval 
                                                        = 
                                                        0.5f
                                                        ;
                                                        private 
                                                        bool 
                                                        isShooting 
                                                        = 
                                                        false
                                                        ;
                                                        private 
                                                        float 
                                                        timeSinceLastShot 
                                                        = 
                                                        0f
                                                        ;
                                                        void
                                                        Update
                                                        ()
                                                        { 
                                                        if 
                                                        (Input
                                                        .
                                                        GetMouseButton
                                                        (
                                                        0
                                                        )
                                                        )
                                                        {
                                                        isShooting
                                                        = 
                                                        true
                                                        ;
                                                        }
                                                        else
                                                        {
                                                        isShooting 
                                                        = 
                                                        false
                                                        ;
                                                        timeSinceLastShot 
                                                        = 
                                                        0f
                                                        ;
                                                        }
                                                        if 
                                                        (
                                                        isShooting
                                                        )
                                                        {
                                                        timeSinceLastShot 
                                                        += 
                                                        Time
                                                        .
                                                        deltaTime
                                                        ;
                                                        if 
                                                        (
                                                        timeSinceLastShot 
                                                        >= 
                                                        shootingInterval
                                                        )
                                                        {
                                                        ShootObject
                                                        (
                                                        )
                                                        ;
                                                        timeSinceLastShot 
                                                        = 
                                                        0f
                                                        ;
                                                        }
                                                        }
                                                        else
                                                        {
                                                        if 
                                                        (
                                                        Input
                                                        .
                                                        GetMouseButtonDown
                                                        (
                                                        0
                                                        )
                                                        )
                                                        {
                                                        ShootObject
                                                        (
                                                        )
                                                        ;
                                                        }
                                                        }
                                                        }
                                                        void 
                                                        ShootObject
                                                        (
                                                        )
                                                        {
                                                        GameObject 
                                                        newObject 
                                                        = 
                                                        Instantiate
                                                        (
                                                        prefabToShoot
                                                        , 
                                                        launchPoint
                                                        .
                                                        position
                                                        , 
                                                        Quaternion
                                                        .
                                                        identity
                                                        )
                                                        ;
                                                        Rigidbody 
                                                        rb 
                                                        = 
                                                        newObject
                                                        .
                                                        GetComponent
                                                        <
                                                        Rigidbody
                                                        >
                                                        (
                                                        )
                                                        ;
                                                        if 
                                                        (
                                                        rb
                                                        !=
                                                        null
                                                        )
                                                        {
                                                        Vector3 
                                                        shootingDirection 
                                                        = 
                                                        launchPoint
                                                        .
                                                        forward
                                                        ;
                                                        rb
                                                        .
                                                        AddForce
                                                        (
                                                        shootingDirection 
                                                        * 
                                                        shootingForce
                                                        , 
                                                        ForceMode
                                                        .
                                                        Impulse
                                                        )
                                                        ;
                                                        }
                                                        else
                                                        {
                                                        Debug
                                                        .
                                                        LogWarning
                                                        (
                                                        "Rigidbody component not found on the prefab!"
                                                        )
                                                        ;
                                                        }
                                                        }
                                                        }